### ISSUE TITLE
NuGet installation fails

### ISSUE THREAD

**Issue by mnaoumov** [ForNeVeR/tdlib.native#30]
> Install-Package : Could not install package 'tdlib.native 1.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any 
> assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ForNeVeR** [comment]
Could you please share the project for me to easier reproduce the issue? Thanks.

I'm not sure how it is supposed to work in a .NET Framework project (since the DLL layout is a bit different), but the libraries here are purely native, so ideally it should work.

**Comment by mnaoumov** [comment]
There is nothing to share. It was a brand new empty console project with
.NET Framework 4.8

**Comment by ForNeVeR** [comment]
I am sorry, but it seems there was something to share, since I wasn't able to reproduce your issue. Here's my `.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="tdlib.native" Version="1.6.0" />
    </ItemGroup>

</Project>
```

This passes `dotnet restore` just fine, no warnings are shown.

Is it possible that you use old (pre-Core) SDK for some reason? If you do, then I advise you against it. I don't know if it old SDK supports _any_ layout for native artifacts; most likely, it doesn't.
